# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

RSpec/MultipleExpectations:
  Max: 2

RSpec/ExampleLength:
  Max: 10

# context の説明文を日本語で記述しているため英語プレフィックス規則を無効化
RSpec/ContextWording:
  Enabled: false
